#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence


SMOKE_TMP_PARENT = Path("/tmp")
SMOKE_TMP_PREFIX = "xona-smoke-"
SMOKE_ROOT_MARKER = ".xona-disposable-smoke-root"
SYNTHETIC_MEDIA_BYTES = b"xona disposable synthetic media\n"


class SmokeSafetyError(ValueError):
    pass


@dataclass(frozen=True)
class SyntheticCandidate:
    source_id: str
    title: str
    url: str


@dataclass(frozen=True)
class SmokePreview:
    operation: str
    source_path: Path
    target_path: Path
    candidate: SyntheticCandidate


@dataclass(frozen=True)
class DisposableSmokeResult:
    status: str
    root: Path
    source_path: Path
    target_path: Path
    bytes_copied: int
    sha256: str
    cleaned_up: bool

    def to_json(self) -> dict[str, object]:
        payload = asdict(self)
        payload["root"] = str(self.root)
        payload["source_path"] = str(self.source_path)
        payload["target_path"] = str(self.target_path)
        return payload


class DisposableSmokeSandbox:
    def __init__(
        self,
        root: Path | str,
        *,
        user_media_roots: Iterable[Path | str] = (),
    ) -> None:
        self.root = validate_disposable_root(root)
        self._user_media_roots = tuple(Path(path) for path in user_media_roots)

    def path(self, path: Path | str, *, require_exists: bool = False) -> Path:
        return canonicalize_path(
            path,
            root=self.root,
            require_exists=require_exists,
            user_media_roots=self._user_media_roots,
        )

    def mkdir(self, path: Path | str) -> Path:
        target = self.path(path, require_exists=False)
        target.mkdir(parents=True, exist_ok=True)
        return self.path(target, require_exists=True)

    def write_bytes(self, path: Path | str, content: bytes) -> Path:
        target = self.path(path, require_exists=False)
        parent = self.path(target.parent, require_exists=True)
        if not parent.is_dir():
            raise SmokeSafetyError(f"Parent is not a directory: {parent}")
        if target.exists() or target.is_symlink():
            raise SmokeSafetyError(f"Target already exists: {target}")
        with target.open("xb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        return self.path(target, require_exists=True)

    def read_bytes(self, path: Path | str) -> bytes:
        source = self.path(path, require_exists=True)
        if not source.is_file():
            raise SmokeSafetyError(f"Source is not a file: {source}")
        with source.open("rb") as handle:
            return handle.read()

    def copy_file(self, source: Path | str, target: Path | str) -> Path:
        source_path = self.path(source, require_exists=True)
        target_path = self.path(target, require_exists=False)
        parent = self.path(target_path.parent, require_exists=True)
        if not source_path.is_file():
            raise SmokeSafetyError(f"Source is not a file: {source_path}")
        if not parent.is_dir():
            raise SmokeSafetyError(f"Parent is not a directory: {parent}")
        if target_path.exists() or target_path.is_symlink():
            raise SmokeSafetyError(f"Target already exists: {target_path}")
        with source_path.open("rb") as source_handle, target_path.open("xb") as target_handle:
            shutil.copyfileobj(source_handle, target_handle)
            target_handle.flush()
            os.fsync(target_handle.fileno())
        return self.path(target_path, require_exists=True)


def create_disposable_root() -> Path:
    raw_root = Path(tempfile.mkdtemp(prefix=SMOKE_TMP_PREFIX, dir=str(SMOKE_TMP_PARENT)))
    root = _canonicalize_absolute_path(raw_root, require_exists=True)
    _ensure_tmp_smoke_root_shape(root)
    marker = root / SMOKE_ROOT_MARKER
    with marker.open("x", encoding="utf-8") as handle:
        handle.write("generated by scripts/disposable_smoke.py\n")
        handle.flush()
        os.fsync(handle.fileno())
    return validate_disposable_root(root)


def validate_disposable_root(root: Path | str, *, require_marker: bool = True) -> Path:
    root_path = _canonicalize_absolute_path(Path(root), require_exists=True)
    _ensure_tmp_smoke_root_shape(root_path)
    if not root_path.is_dir():
        raise SmokeSafetyError(f"Disposable root is not a directory: {root_path}")
    marker = root_path / SMOKE_ROOT_MARKER
    if require_marker and (marker.is_symlink() or not marker.is_file()):
        raise SmokeSafetyError(f"Disposable root was not generated by this smoke harness: {root_path}")
    return root_path


def cleanup_disposable_root(root: Path | str) -> None:
    root_path = validate_disposable_root(root)
    shutil.rmtree(root_path)


def canonicalize_path(
    path: Path | str,
    *,
    root: Path | str | None = None,
    require_exists: bool = True,
    user_media_roots: Iterable[Path | str] = (),
) -> Path:
    candidate = Path(path)
    if _contains_nul(candidate):
        raise SmokeSafetyError("Path contains NUL")

    root_path: Path | None = None
    if root is not None:
        root_path = validate_disposable_root(root)
        if not candidate.is_absolute():
            candidate = root_path / candidate
    elif not candidate.is_absolute():
        raise SmokeSafetyError(f"Path must be absolute: {candidate}")

    resolved = _canonicalize_absolute_path(candidate, require_exists=require_exists)
    if root_path is not None:
        _ensure_inside_root(resolved, root_path)
    _ensure_not_user_media(resolved, user_media_roots)
    return resolved


def canonicalize_unique_paths(
    paths: Sequence[Path | str],
    *,
    root: Path | str,
    require_exists: bool = True,
    user_media_roots: Iterable[Path | str] = (),
) -> tuple[Path, ...]:
    seen: dict[str, Path | str] = {}
    resolved_paths: list[Path] = []
    for original in paths:
        resolved = canonicalize_path(
            original,
            root=root,
            require_exists=require_exists,
            user_media_roots=user_media_roots,
        )
        key = os.path.normcase(str(resolved))
        if key in seen:
            raise SmokeSafetyError(
                f"Ambiguous equivalent paths: {seen[key]!s} and {original!s} both resolve to {resolved}"
            )
        seen[key] = original
        resolved_paths.append(resolved)
    return tuple(resolved_paths)


def synthetic_xchina_search(query: str) -> list[SyntheticCandidate]:
    normalized = query.strip() or "SMOKE-001"
    return [
        SyntheticCandidate(
            source_id=normalized,
            title="Synthetic Smoke Movie",
            url=f"https://example.invalid/xchina/{normalized}",
        )
    ]


def build_synthetic_preview(
    *,
    sandbox: DisposableSmokeSandbox,
    source_path: Path | str,
    candidate: SyntheticCandidate,
) -> SmokePreview:
    source = sandbox.path(source_path, require_exists=True)
    target = sandbox.path(
        Path("organized") / candidate.source_id / f"{candidate.title}.mp4",
        require_exists=False,
    )
    return SmokePreview(
        operation="copy",
        source_path=source,
        target_path=target,
        candidate=candidate,
    )


def run_disposable_smoke(*, keep_root: bool = False) -> DisposableSmokeResult:
    root = create_disposable_root()
    result: DisposableSmokeResult | None = None
    try:
        sandbox = DisposableSmokeSandbox(root)
        sandbox.mkdir("incoming")
        sandbox.mkdir("organized")
        sandbox.mkdir("work")

        source = sandbox.write_bytes("incoming/SMOKE-001.mp4", SYNTHETIC_MEDIA_BYTES)
        candidates = synthetic_xchina_search("SMOKE-001")
        if len(candidates) != 1:
            raise SmokeSafetyError("Synthetic search did not return exactly one candidate")

        preview = build_synthetic_preview(
            sandbox=sandbox,
            source_path=source,
            candidate=candidates[0],
        )
        sandbox.mkdir(Path("organized") / candidates[0].source_id)
        canonicalize_unique_paths(
            [preview.source_path, preview.target_path.parent, root / "work"],
            root=root,
            require_exists=True,
        )
        copied = sandbox.copy_file(preview.source_path, preview.target_path)
        copied_bytes = sandbox.read_bytes(copied)
        expected_sha256 = _sha256_bytes(SYNTHETIC_MEDIA_BYTES)
        observed_sha256 = _sha256_bytes(copied_bytes)
        if observed_sha256 != expected_sha256:
            raise SmokeSafetyError("Copied media hash did not match source media hash")

        result = DisposableSmokeResult(
            status="passed",
            root=root,
            source_path=source,
            target_path=copied,
            bytes_copied=len(copied_bytes),
            sha256=observed_sha256,
            cleaned_up=False,
        )
    finally:
        if not keep_root:
            cleanup_disposable_root(root)

    if result is None:
        raise SmokeSafetyError("Disposable smoke did not produce a result")
    return DisposableSmokeResult(
        status=result.status,
        root=result.root,
        source_path=result.source_path,
        target_path=result.target_path,
        bytes_copied=result.bytes_copied,
        sha256=result.sha256,
        cleaned_up=not keep_root,
    )


def _canonicalize_absolute_path(path: Path, *, require_exists: bool) -> Path:
    if _contains_nul(path):
        raise SmokeSafetyError("Path contains NUL")
    if not path.is_absolute():
        raise SmokeSafetyError(f"Path must be absolute: {path}")
    _ensure_no_symlink_components(path)
    if require_exists and not path.exists():
        raise SmokeSafetyError(f"Path does not exist: {path}")
    try:
        return path.resolve(strict=require_exists)
    except FileNotFoundError as exc:
        raise SmokeSafetyError(f"Path does not exist: {path}") from exc
    except OSError as exc:
        raise SmokeSafetyError(f"Path cannot be resolved safely: {path}") from exc


def _ensure_tmp_smoke_root_shape(path: Path) -> None:
    tmp_parent = SMOKE_TMP_PARENT.resolve(strict=True)
    if path.parent != tmp_parent or not path.name.startswith(SMOKE_TMP_PREFIX):
        raise SmokeSafetyError(f"Disposable root must match /tmp/{SMOKE_TMP_PREFIX}*: {path}")


def _ensure_no_symlink_components(path: Path) -> None:
    current = path
    while True:
        try:
            if current.is_symlink():
                raise SmokeSafetyError(f"Path includes a symlink: {current}")
        except OSError as exc:
            raise SmokeSafetyError(f"Path cannot be checked safely: {current}") from exc
        if current.parent == current:
            return
        current = current.parent


def _ensure_inside_root(path: Path, root: Path) -> None:
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise SmokeSafetyError(f"Path is outside disposable smoke root: {path}") from exc


def _ensure_not_user_media(path: Path, user_media_roots: Iterable[Path | str]) -> None:
    for root in user_media_roots:
        root_path = Path(root)
        if not root_path.is_absolute():
            root_path = Path.cwd() / root_path
        try:
            resolved_root = _canonicalize_absolute_path(root_path, require_exists=root_path.exists())
        except SmokeSafetyError:
            resolved_root = root_path.resolve(strict=False)
        try:
            path.relative_to(resolved_root)
        except ValueError:
            continue
        raise SmokeSafetyError(f"Path is under a user media root: {path}")


def _contains_nul(path: Path | str) -> bool:
    return "\0" in os.fspath(path)


def _sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run Xona's disposable synthetic smoke harness.")
    parser.add_argument(
        "--keep-root",
        action="store_true",
        help="Leave the generated /tmp/xona-smoke-* root in place for inspection.",
    )
    args = parser.parse_args(argv)

    result = run_disposable_smoke(keep_root=args.keep_root)
    print(json.dumps(result.to_json(), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
